remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
title: Stellar Astro Developer Portfolio
description: Boost Your Professional Online Presence with a Customizable, Minimalistic Astro Template Optimized for Performance and SEO.
